[workspace]

members = [
    "crates/wasi-common",
    "crates/blockless-drivers",
    "crates/blockless-env",
    "blockless",
    "simple-cli",
]

[patch.crates-io]
wasi-common = {path = "crates/wasi-common"}