[package]
name = "blockless-drivers"
version = "0.1.0"
authors = ["Join.G"]
description = "blockless drivers"
keywords = ["blockless", "driver"]
readme = "README.md"
edition = "2021"

[dependencies]
blockless-drivers-macro = {path = "macro"}
wasmtime-wasi = "0.36.0"
wiggle = "0.36.0"
anyhow = "1"
cap-std = "0.24.1"
log = "0.4"
async-trait = "0.1"
dlopen = "0.1"
reqwest = {version = "0.11", features = ["stream"]}
serde_urlencoded = "0.7"
json = {version = "0.12.4"}
wasi-cap-std-sync = {path = "../wasi-common/cap-std-sync"}
wasi-common = {path = "../wasi-common"}
url = "2.2"

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.tokio]
version = "1"
features = ["net"]

[dependencies.blockless-multiaddr]
path = "../blockless-multiaddr"
