on:
  release:
    types: [created]

name: Release

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: target/release/.fingerprint
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: target/release/examples
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: target/release/build
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: target/release/incremental
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: target/release/examples
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          filename: ../../blockless-runtime.${{ matrix.os }}.x64.zip
          directory: target/release
          path: .
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: blockless-runtime.${{ matrix.os }}.x64.zip
          asset_name: blockless-runtime.${{ matrix.os }}.x64.zip
          asset_content_type: application/gzip
