on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "tag"
        required: true

name: Release

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.event.inputs.tag_name }}
          tag_name: ${{ github.event.inputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Tar files
        run: |
          rm -rf target/release/build
          rm -rf target/release/deps
          rm -rf target/release/examples
          rm -rf target/release/incremental
          tar -cvzf blockless-runtime.${{ matrix.os }}.amd64.tar.gz target/release
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: blockless-runtime.${{ matrix.os }}.amd64.tar.gz
          asset_name: blockless-runtime.${{ matrix.os }}.amd64.tar.gz
          asset_content_type: application/gzip
